# Generated by Django 3.1 on 2020-08-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidadores',
            name='archivoCertAsp',
            field=models.FileField(upload_to='cuidadores/archivos'),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='archivoCertDomAsp',
            field=models.FileField(upload_to='cuidadores/archivos'),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='archivoCertReinc',
            field=models.FileField(upload_to='cuidadores/archivos'),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='archivoDniAsp',
            field=models.FileField(upload_to='cuidadores/archivos'),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='archivoGeriatria',
            field=models.FileField(upload_to='cuidadores/archivos'),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='arhivoCertPsfAsp',
            field=models.FileField(upload_to='cuidadores/archivos'),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoClinica',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoDom',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoFamiliar',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoInst',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='direcClinica',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='direcInst',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='nombreClinica',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='nombreInst',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
