# Generated by Django 3.1 on 2020-08-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='apCol',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cuilCol',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='dniCol',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nomCol',
            field=models.CharField(max_length=80),
        ),
    ]
