# Generated by Django 3.1 on 2020-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='voluntarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('dni', models.IntegerField()),
                ('cuil', models.CharField(max_length=11)),
                ('lugarNac', models.CharField(max_length=80)),
                ('fechaNac', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=80)),
                ('barrio', models.CharField(max_length=80)),
                ('localidad', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('rdEstudiante', models.CharField(max_length=2)),
                ('estudios', models.CharField(blank=True, max_length=80, null=True)),
                ('rdOrg', models.CharField(max_length=2)),
                ('nomOrg', models.CharField(blank=True, max_length=80, null=True)),
                ('rdTrabaja', models.CharField(max_length=2)),
                ('lugarTrab', models.CharField(blank=True, max_length=80, null=True)),
                ('rdProfesion', models.CharField(max_length=2)),
                ('profestion', models.CharField(blank=True, max_length=80, null=True)),
                ('trLunes', models.BooleanField(default=False)),
                ('hrDesdeLun', models.TimeField()),
                ('hrHastaLun', models.TimeField()),
                ('trMartes', models.BooleanField(default=False)),
                ('hrDesdeMar', models.TimeField()),
                ('hrHastaMar', models.TimeField()),
                ('trMierdoles', models.BooleanField(default=False)),
                ('hrDesdeMier', models.TimeField()),
                ('hrHastaMier', models.TimeField()),
                ('trJueves', models.BooleanField(default=False)),
                ('hrDesdeJuev', models.TimeField()),
                ('hrHastaJuev', models.TimeField()),
                ('trViernes', models.BooleanField(default=False)),
                ('hrDesdeVier', models.TimeField()),
                ('hrHastaVier', models.TimeField()),
                ('trSabado', models.BooleanField(default=False)),
                ('hrDesdeSab', models.TimeField()),
                ('hrHastaSab', models.TimeField()),
                ('trDomingo', models.BooleanField(default=False)),
                ('hrDesdeDom', models.TimeField()),
                ('hrHastaDom', models.TimeField()),
                ('comentario', models.CharField(max_length=800)),
                ('rdLeyVol', models.CharField(max_length=2)),
            ],
        ),
    ]
