# Generated by Django 3.1 on 2020-08-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedores',
            name='cuitPersoneria',
            field=models.BigIntegerField(default=0),
        ),
    ]
