# Generated by Django 3.1 on 2020-08-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0002_auto_20200818_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarios',
            name='inputDniBenef',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarios',
            name='inputNombreBenef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comedores',
            name='cuitPersoneria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comedores',
            name='personeria',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='comedores',
            name='tipoDeporte',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='comedores',
            name='tipoRemuneracionDS',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
