# Generated by Django 3.1 on 2020-08-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0002_auto_20200826_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedores',
            name='cuitPersoneria',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
