# Generated by Django 3.1 on 2020-08-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0002_voluntarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedores',
            name='dniRes',
            field=models.BigIntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='dni',
            field=models.BigIntegerField(max_length=9),
        ),
    ]
