# Generated by Django 3.1 on 2020-08-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0003_auto_20200826_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedores',
            name='tipoDeporte',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='comedores',
            name='tipoRemuneracionDS',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoClinica',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoDom',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoFamiliar',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='contactoInst',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='direcClinica',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='direcInst',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='nombreClinica',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='nombreInst',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='rdLugarExperiencia',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='estudios',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='lugarTrab',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='nomOrg',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='profestion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
