# Generated by Django 3.1 on 2020-08-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0003_auto_20200813_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedores',
            name='perteneceOrg',
        ),
    ]
