# Generated by Django 3.1 on 2020-08-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0003_auto_20200820_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedores',
            name='dniRes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='dni',
            field=models.BigIntegerField(),
        ),
    ]
