# Generated by Django 3.1 on 2020-08-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0004_remove_comedores_perteneceorg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedores',
            name='apellidoRes',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='contactoRes',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='cuilRes',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='dniRes',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='emailRes',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='nombreRes',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='srvComedor',
        ),
        migrations.RemoveField(
            model_name='comedores',
            name='srvMerendero',
        ),
    ]
