# Generated by Django 3.1 on 2020-08-22 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0005_voluntarios_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarios',
            name='dias',
        ),
        migrations.AddField(
            model_name='comedores',
            name='dias',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
