# Generated by Django 3.1 on 2020-08-22 23:07

import comedores.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0006_auto_20200822_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedores',
            name='dias',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='archivoCertReinc',
            field=models.FileField(upload_to='archivos/cuidadores', validators=[comedores.validators.file_size]),
        ),
    ]
